### ISSUE TITLE
Issue while building 

### ISSUE THREAD

**Issue by atulraj85** [AmanBhatt0910/Amit-sir-task#3]
![image](https://github.com/AmanBhatt0910/Amit-sir-task/assets/121156542/af2053a5-71e8-4a69-a7bb-1181e7681301)

Check if the alias "@" is working fine.

**Comment by AmanBhatt0910** [comment]
Its working fine in my machine.

**Comment by AmanBhatt0910** [comment]
Its working fine in my machine.

**Comment by AmanBhatt0910** [comment]
Its working fine in my machine.
